"""Add restaurant_id to users

Revision ID: 4c88b66c50c0
Revises: 82f2eaae0f46
Create Date: 2025-03-11 11:22:32.144515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c88b66c50c0'
down_revision: Union[str, None] = '82f2eaae0f46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('restaurant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'restaurants', ['restaurant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'restaurant_id')
    # ### end Alembic commands ###
